### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by IzzySoft** [BijoySingh/Scarlet-Notes#1] opened 2017-11-02 22:10 UTC
I've the feeling your app would be a perfect candidate for the official F-Droid repository: it looks very privacy friendly and seems to have no proprietary dependencies, while offering a good value to users. Hence [I've submitted a request for packaging](https://gitlab.com/fdroid/rfp/issues/408) and hope you'll support that (they will build your app from your sources then, but might need a little help setting things up; if they really need the help they will say so in the linked issue).

Until it becomes available there, it already [is available via my F-Droid compatible repo](https://apt.izzysoft.de/fdroid/index/apk/com.bijoysingh.quicknote), automatically picking updates as soon as you update the APK.

Thinks for you to consider (most of those you're probably already aware of):

* make sure new APKs always have their `versionCode` increased and the `versionName` updated appropriately, so they are accepted as updates
* to make updates easier (especially for the official repo), consider tagging releases (using the `versionName`, prepended with a `v`, as tag – so e.g. version 1.2.3 should be tagged `v1.2.3`)

Thanks for making your great app available open-source!

**Comment by BijoySingh** [comment] 2017-11-25 10:56
Okay. Thanks IzzySoft. I will make the versionNames with `v` tag moving forward.

**Comment by IzzySoft** [comment] 2017-11-25 11:27
Thanks! Have you seen on the linked RFP (Request For Packaging) what's keeping F-Droid from picking it up? It's a custom Maven repo (http://dl.bintray.com/bijoysingh693/maven) you're using. F-Droid requires that to be a "trusted repository". Any chance you could fix that? Hopefully helpful reference: [Which libraries and dependencies are good to use?](https://f-droid.org/de/docs/FAQ_-_App_Developers/#which-libraries-and-dependencies-are-good-to-use)

**Comment by relan** [comment] 2017-11-25 13:58
Hi,

F-Droid maintainer here. I'd like to see Material Notes on F-Droid main repository. Theremare two issues hindering this:

1. Releases aren't tagged. Without proper git tags we don't know what snapshot to check out (F-Droid builds app from source code). Version name does not need to have "v" prefix.

2. We can compile com.github.bijoysingh:* libraries from source, but again we need to know which commit to check out. Tags would help with this too.

**Comment by BijoySingh** [comment] 2017-11-25 14:09
Hi relan. I realised that the issue is because one of my libraries isn't fetching from JCenter even though it's linked to it. I am trying to resolve that, so I don't need to mention my custom maven in the repositories

Cool. Got that. Will tag releases with the version numbers. 

Thanks

**Comment by relan** [comment] 2017-11-25 14:22
> I am trying to resolve that, so I don't need to mention my custom maven in the repositories

If you manage to serve your libraries from JCenter and remove custom Maven repo, this will be perfect!

**Comment by BijoySingh** [comment] 2017-11-25 14:28
Yeah, the sad thing is that I have already linked all my libraries to JCenter. One of them is have issues, I am guessing some problem from Bintray's side. I am notifying the issue to them, hopefully it will be resolved soon.

**Comment by BijoySingh** [comment] 2017-12-02 15:58
@relan @IzzySoft the release v3.2.0 doesnt have dependency on custom repo, and works with JCenter. Hope it solves this issue.

**Comment by relan** [comment] 2017-12-02 18:13
Added in https://gitlab.com/fdroid/fdroiddata/commit/fb221527c1502ad7c9fcd2562581f2986ad7328a. Will be available in a couple of days. Thanks!

Please note that F-Droid will be able to pull new releases automatically only if `versionName` corresponds to Git tag name. For example, version `4.0.0` should be tagged as `v4.0.0`.

**Comment by BijoySingh** [comment] 2017-12-02 18:53
Awesome!

**Comment by IzzySoft** [comment] 2017-12-10 17:45
@BijoySingh With the "official repo" taking over successfully now, I'll "unlist" the app on my end. Feel free to contact me should the need arise, I'd re-establish it anytime. Thanks so far!

**Comment by BijoySingh** [comment] 2017-12-10 23:05
@IzzySoft I would like to make something like a cloud sync. Ideally I would prefer Firebase / Drive Backup, but for both I will need to add API tokens etc, which I think are a bit unsafe to put in a public repo.

Further even if I do, the key will not match for when you sign the APK. Is there something you tend to do in this case or you consider it ok that F-Droid version of the app wont support backup? 

If there's some other secure and scalable way of doing it, can you tell me.

**Comment by IzzySoft** [comment] 2017-12-10 23:26
F-Droid would no longer accept your app if you integrated Firebase. I wouldn't sign your APKs anyway (which is why I needed the `.apk` files), so it would work with my repo. Still, I wouldn't find that ideal.

As you ask me how I'd approach this, I'll give you a direct answer. I'd leave that out of the app for multiple reasons:

1. it's an editor / a note-taking app. Focus on that :wink:
1. I always prefer separate apps for those things. Here that would ideally mean the Notes app even coming without any network permissions – but instead either saving all documents on shared storage (i.e. internal/external SD) or at least allowing to sync its data to that location. To sync with network ressources I'd use a separate app which focuses on that. No need to have multiple apps implementing the same stuff.
1. it's open source. Better not mingle it with proprietary dependencies. Especially not with Firebase or other Google stuff: many of us tin-foils especially want to avoid that.

If you really insist on integrating that, I'd strongly recommend using a separate flavour for that (which then also uses a different package name). That way at least the two can be kept apart, and you avoid issues with F-Droid.

Alternatively, put that into a "plugin"/"addon", then it's completely separated :wink:

**Comment by genofire** [comment] 2018-01-28 23:48
Would like to use current Version by F-Droid (without thinks like firebase ;( )

**Comment by BijoySingh** [comment] 2018-10-10 08:09
@IzzySoft Is there a way to find out why the Fdroid stopped updating?

I can imagine it would be because of firebase, but the "app" target should not have that as a dependency. Or do you blacklist based on the dependency just being in the repository?

**Comment by IzzySoft** [comment] 2018-10-11 07:05
@BijoySingh usually via [this page](https://f-droid.org/wiki/page/com.bijoysingh.quicknote) – which seems to be wrong, saying F-Droid has the latest version. As you seem to build `versionName`/`versionCode` dynamically somehow, I was not able to check whether the former matches the tag name, for example? A mismatch there would explain things. If that's not the case, I'd recommend [opening an issue with fdroiddata](https://gitlab.com/fdroid/fdroiddata/issues/) so a maintainer can take a closer look. According to your app's Metadata, new tags should be fetched automatically.

**Comment by licaon-kter** [comment] 2019-02-27 15:10
Could you keep tagging format consistent?  `v6.9.5`....`6.6.3`....`v5.9.7`

Each time you put an extra `v` or take away one the F-Droid auto update process breaks and no new version is build.

Ref: https://gitlab.com/fdroid/fdroiddata/commit/5b4cd4901e488656a330570315a201246925a468

/close this

**Comment by BijoySingh** [comment] 2019-02-27 16:23
Sorry for that @licaon-kter. I had been putting the `v` before but I missed it on `6.6.3`, so I corrected it after... Ofc that meant things broke twice :p

Will continue putting `v` moving forward.

**Closed** 2019-02-27 16:24 UTC
